window.hicoLearningData = {
  modules: [
    {
      id: 'hico', title: 'What is HICO?', navTitle: 'HICO', domain: 'Grunnlag', duration: '8 min',
      goal: 'Forstaa hvorfor HICO modellerer objekter og relasjoner i stedet for aa samle alt i dokumenter.',
      intro: 'HICO brukes til aa strukturere, koble og haandtere informasjon gjennom produktets levetid. Verdien ligger ikke bare i dataene, men i at informasjon kan spores, valideres og brukes videre.',
      example: 'Vi har faatt et nytt fartoy. I stedet for aa starte med et regneark modellerer vi produktet, strukturen og stotteinformasjonen som objekter som kan kobles sammen.',
      case: 'ASK2026;10 skal leveres til en kunde. Hva maa vi forstaa foer vi bestemmer hvilke HICO-objekter vi skal opprette?',
      caseAnswer: 'Start med virkeligheten som skal modelleres: et konkret produkt, dets struktur, stoettebehov og informasjon som skal brukes videre. Velg objekter ut fra hvilken rolle informasjonen har.',
      nodes: ['hico','sseries'], concepts: ['HICO','IPS','ILS','Masterdata','Objekt','Relasjon','Gjenbruk'],
      questions: [
        {difficulty:'basic', prompt:'Et vedlikeholdsteam, en reservedelsliste og en teknisk publikasjon beskriver samme pumpe. Hvorfor modellere pumpen som et gjenbrukbart objekt?', options:['For aa kunne koble samme identitet til flere brukssteder uten aa kopiere masterdata','For aa tvinge alle team til aa bruke samme dokumentmal','For aa fjerne behovet for produktstruktur','For aa lagre PDF-filer i en felles mappe'], answer:0, explanation:'Et objekt kan gjenbrukes og kobles til flere sammenhenger. Kopierte beskrivelser driver fra hverandre naar informasjon endres.', concepts:['HICO','Masterdata','Gjenbruk']},
        {difficulty:'medium', prompt:'Et regneark inneholder en Maintenance Task som en tekstcelle. Hva gaar tapt sammenlignet med en strukturert modell?', options:['Muligheten til aa skrive ut regnearket','Muligheten til aa koble oppgaven til struktur, ressurser og dokumentasjon','Muligheten til aa bruke norske tegn','Muligheten til aa lagre en fil lokalt'], answer:1, explanation:'En strukturert oppgave kan knyttes til produktstruktur og andre objekter, valideres og brukes som grunnlag videre. Ren tekst uttrykker ikke disse koblingene.', concepts:['Objekt','Relasjon','Maintenance Task']},
        {difficulty:'medium', prompt:'En kollega foreslaar aa laere alle HICO-objektnavn utenat foer de modellerer noe. Hva er en bedre start?', options:['Lage flest mulig tomme objekter','Forstaa hva slags virkelighet og informasjon som skal modelleres','Begynne med eksportmalene','Importere alle tilgjengelige regneark'], answer:1, explanation:'Objektnavn gir lite mening uten kontekst. Start med produktet og informasjonsbehovet, og velg deretter objekter etter hvorfor de finnes.', concepts:['HICO','Objekt']},
        {difficulty:'hard', prompt:'Den samme pumpen brukes i to fartoy. Vedlikeholdsoppgaven endres etter en ny analyse. Hva er fordelen ved en strukturert relasjonsmodell?', options:['Begge fartoy faar automatisk identisk konfigurasjon','Oppgaven kan vedlikeholdes som ett objekt og kobles til flere relevante strukturer','Endringen trenger ikke versjoneres','All teknisk dokumentasjon blir automatisk godkjent'], answer:1, explanation:'Gjenbruk kan redusere duplisering, mens koblingene viser hvor objektet brukes. Endringen maa fortsatt vurderes og styres; modellen garanterer ikke automatisk godkjenning.', concepts:['Relasjon','Gjenbruk','Maintenance Task']},
        {difficulty:'hard', prompt:'Et prosjekt vil lage en separat kopi av alle masterdata for hvert fagomraade. Hva er den viktigste risikoen?', options:['Objektene faar for korte navn','Kopier kan bli motstridende og miste sporbarhet naar informasjon endres','S-Series-spesifikasjonene blir automatisk ugyldige','Brukeren kan ikke se objektene i et diagram'], answer:1, explanation:'Kopier skaper flere versjoner av det som skal vaere samme informasjon. Gjenbrukbare objekter med kontrollerte relasjoner gir bedre sporbarhet.', concepts:['Masterdata','Gjenbruk','Relasjon']},
        {difficulty:'medium', prompt:'En kunde spoer om forskjellen paa en standard og HICO. Hvilket svar beskriver forholdet best?', options:['HICO er standarden som erstatter alle S-Series-regler','S-Series beskriver standardiserte modeller og dataomraader; HICO haandterer modellert informasjon','HICO og S-Series er to navn paa samme database','S1000D er HICO-brukerflaten'], answer:1, explanation:'Standardene beskriver blant annet modeller og dataomraader. HICO er systemet der informasjonen modelleres og kobles.', concepts:['HICO','S-Series']}
      ]
    },
    {
      id: 's-series', title: 'The S-Series', navTitle: 'S-Series', domain: 'Standarder', duration: '8 min',
      goal: 'Kjenne igjen hvilket IPS-problem sentrale S-Series-spesifikasjoner adresserer, og hvordan omraadene kan dele informasjon.',
      intro: 'S-Series er en familie av spesifikasjoner for ulike deler av Integrated Product Support. Du trenger ikke memorere alt; du maa kunne velge relevant fagomraade og forstaa hvor data kan moete hverandre.',
      example: 'Fartoyets pumpe trenger reservedelsdata, en vedlikeholdsanalyse og en teknisk prosedyre. Dette er ulike fagomraader, men de kan referere til de samme produktobjektene.',
      case: 'ASK2026;10 trenger en reservedel, vedlikeholdsanalyse og teknisk dokumentasjon. Hvilke standardomraader er mest relevante?',
      caseAnswer: 'S2000M dekker material og forsyning, S3000L dekker logistikkstoetteanalyse og vedlikehold, og S1000D dekker teknisk dokumentasjon. De er ulike fagomraader som kan arbeide med sammenhengende informasjon.',
      nodes: ['s2000m','s3000l','s1000d','ips'], concepts: ['S-Series','S1000D','S2000M','S3000L','IPS','ILS'],
      questions: [
        {difficulty:'basic',prompt:'En gruppe skal velge standardomraade for teknisk vedlikeholdsanalyse. Hvilken er mest direkte relevant?',options:['S1000D','S2000M','S3000L','XSL'],answer:2,explanation:'S3000L gjelder logistics support analysis, inkludert arbeid knyttet til stoette og vedlikehold.',concepts:['S3000L']},
        {difficulty:'medium',prompt:'Reservedels- og forsyningsinformasjon skal modelleres etter relevant S-Series-omraade. Hva boer teamet undersoeke foerst?',options:['S1000D','S2000M','S4000P','XSL'],answer:1,explanation:'S2000M er det mest direkte material- og forsyningsomraadet i denne familien.',concepts:['S2000M']},
        {difficulty:'medium',prompt:'Vedlikeholdsprosedyren skal publiseres som strukturert teknisk dokumentasjon. Hvilken standard er mest relevant for publikasjonens innhold?',options:['S1000D','S2000M','S5000F','LCN'],answer:0,explanation:'S1000D er omraadet for teknisk dokumentasjon. Det erstatter ikke analyse- eller materialarbeidet, men kan bruke relatert informasjon.',concepts:['S1000D','S3000L']},
        {difficulty:'medium',prompt:'Prosjektlederen foreslaar en separat database per S-Series-standard. Hva er den faglige innvendingen?',options:['Standarder kan bare lagres som PDF','Informasjon og HICO-objekter kan brukes paa tvers av fagomraader','S-Series tillater ikke produktnumre','En database per standard gjoer alle koblinger ugyldige'],answer:1,explanation:'S-Series-omraadene er forskjellige, men HICO-informasjon kan knyttes sammen paa tvers. Separate fagomraader betyr ikke at alle data maa dupliseres.',concepts:['S-Series','HICO','Gjenbruk']},
        {difficulty:'hard',prompt:'En Article er etablert i materialarbeidet og trengs senere i produktstrukturen og vedlikeholdsanalysen. Hva viser dette?',options:['At Article bare hoerer til S1000D','At et strukturert objekt kan ha relevans utover omraadet der det foerst ble opprettet','At S2000M automatisk lager vedlikeholdskrav','At alle spesifikasjoner maa ha identiske datastrukturer'],answer:1,explanation:'Et HICO-objekt kan inngaa i flere sammenhenger. Det er koblingen mellom omraadene, ikke identiske standarder, som gir helhet.',concepts:['Article','S-Series','Relasjon']},
        {difficulty:'hard',prompt:'En teknisk publikasjon mangler en analysert vedlikeholdsoppgave. Hvilken arkitekturforstaaelse hjelper best med aa finne bruddet?',options:['Data Module og Maintenance Task er alltid samme objekt','S3000L-analyse og S1000D-publisering er ulike steg som maa kobles gjennom relevant informasjon','S2000M skal skrive prosedyren','XSL bestemmer hvilken vedlikeholdsoppgave som er faglig riktig'],answer:1,explanation:'Analysen og publikasjonen har ulike roller. Oppgaven maa modelleres og kobles til dokumentasjonsflyten; transformasjon lager ikke faglig analyse.',concepts:['S3000L','S1000D','Maintenance Task']}
      ]
    },
    {
      id:'architecture',title:'HICO Architecture',navTitle:'Architecture',domain:'Prosjektmodell',duration:'8 min',
      goal:'Skille IPS Program fra fagprosjektene som organiserer analyse, teknisk dokumentasjon og materialinformasjon.',
      intro:'IPS Program er et overordnet organisatorisk lag. PSA Project, TechPub Project og Material Project har ulike roller, men er ikke dermed separate databaser uten forbindelser.',
      example:'ASK2026;10 hører til et IPS Program. Produktstoette analyseres i et PSA Project; dokumentasjonsregler ligger i et TechPub Project; materialinformasjon organiseres i Material Project.',
      case:'Et fartoyprosjekt trenger PBS, en vedlikeholdsanalyse og S1000D-regler. Maa hvert arbeid opprettes som et eget IPS Program?',
      caseAnswer:'Nei. Ett IPS Program kan organisere flere fagprosjekter. PSA Project og TechPub Project har ulike formål, mens relevante data kan knyttes sammen.',
      nodes:['ips','psa','techpub','material'],concepts:['IPS Program','PSA Project','TechPub Project','Material Project'],
      questions:[
        {difficulty:'basic',prompt:'Et team skal opprette et nytt PSA Project. Hvilket lag gir den overordnede rammen prosjektet inngaar i?',options:['Data Module','IPS Program','Info Code','Breakdown Element'],answer:1,explanation:'IPS Program er det overordnede laget for IPS-relatert prosjektorganisering.',concepts:['IPS Program','PSA Project']},
        {difficulty:'medium',prompt:'En PBS og vedlikeholdsrelatert analyse skal organiseres. Hvilket prosjektomraade er mest relevant?',options:['TechPub Project','PSA Project','Material Project','Fleet'],answer:1,explanation:'PSA Project brukes blant annet til PBS- og vedlikeholdsrelatert analyse.',concepts:['PSA Project','PBS']},
        {difficulty:'medium',prompt:'En kunde skal styre S1000D-relaterte regler og teknisk dokumentasjon. Hvor boer disse prosjektreglene hoere hjemme?',options:['PSA Project','TechPub Project','Device Type Set','Material Project'],answer:1,explanation:'TechPub Project organiserer regler og innstillinger for teknisk dokumentasjon.',concepts:['TechPub Project','S1000D']},
        {difficulty:'medium',prompt:'To PSA Projects ligger under samme IPS Program. Hva kan du slutte om dataene?',options:['De maa ligge i helt separate databaser','Det kan vaere flere fagprosjekter under samme program uten at alle objekter maa dupliseres','Bare ett av prosjektene kan ha en PBS','Det ene prosjektet maa vaere et TechPub Project'],answer:1,explanation:'IPS Program kan romme flere PSA Projects. Prosjektinndeling beskriver arbeidsomraader, ikke automatisk separate databaser.',concepts:['IPS Program','PSA Project','Gjenbruk']},
        {difficulty:'hard',prompt:'Et vedlikeholdsbehov endrer seg og krever en ny analyse, mens publikasjonens S1000D-regler er uendret. Hvilken prosjektendring er mest avgrenset?',options:['Oppdater det relevante PSA Project; behold TechPub Project-reglene uendret hvis de ikke paavirkes','Opprett et nytt IPS Program og kopier alle objekter','Endre Material Project til TechPub Project','Opprett en Article List som erstatter begge prosjektene'],answer:0,explanation:'Prosjektene har ulike fagroller. Endre bare arbeidsomraadet som faktisk er paavirket, og vurder deretter hvilke relasjoner som maa oppdateres.',concepts:['PSA Project','TechPub Project','IPS Program']},
        {difficulty:'hard',prompt:'Et team bruker et felles IPS Program for to produkter, men trenger ulike vedlikeholdsanalyser. Hva er en god modellering?',options:['Ett program kan organisere separate PSA Projects mens relevante masterdata gjenbrukes','Lag to kopier av hver Article og kall dem programdata','Legg analysene inn som Info Codes','Slå sammen produktene til ett Product Type'],answer:0,explanation:'Programmet kan vaere felles samtidig som analysearbeidet deles i PSA Projects. Gjenbrukbare objekter kan knyttes til riktige prosjekter og produkter.',concepts:['IPS Program','PSA Project','Masterdata']}
      ]
    },
    {
      id:'products',title:'Products & Configuration',navTitle:'Products',domain:'Produkter',duration:'8 min',
      goal:'Modellere den konkrete fysiske enheten, produkttyper og variasjoner uten aa duplisere hele strukturen for hver leveranse.',
      intro:'En Product er en konkret fysisk enhet. Product Type og Product Type Variant beskriver felles egenskaper og variasjoner. Configuration og Applicability viser hvilke deler som gjelder for hvilket produkt.',
      example:'ASKELADDEN er produkttypen. ASK2026 kan vaere en variant. ASK2026;10 er det konkrete fartoyet som leveres til en kunde.',
      case:'ASK2026;10 har et navigasjonssystem som mangler paa enkelte andre enheter i samme serie. Hvordan uttrykker modellen forskjellen uten aa kopiere alt?',
      caseAnswer:'Behold gjenbrukbar grunnstruktur, representer den konkrete enheten som Product, og bruk konfigurasjon/applicability for aa uttrykke hva som gjelder for den enheten.',
      nodes:['product','product-type','breakdown','applicability'],concepts:['Product','Product Type','Product Type Variant','Fleet','Configuration','Applicability'],
      questions:[
        {difficulty:'basic',prompt:'Et fartoy har serienummer ASK2026;10 og er fysisk levert til kunden. Hvilket begrep representerer denne enheten?',options:['Product Type','Product Type Variant','Product','Applicability'],answer:2,explanation:'Product representerer den konkrete fysiske enheten, ikke den generelle typen eller hvilken struktur som gjelder.',concepts:['Product']},
        {difficulty:'medium',prompt:'En serie fartoy deler de fleste egenskaper, men en variant har en annen automasjonspakke. Hvilken modell hjelper aa beskrive variasjonen foer de konkrete enhetene?',options:['Product Type og Product Type Variant','Article List og Info Code','PSA Project og Maintenance Level','Data Module og XSL'],answer:0,explanation:'Product Type beskriver den generelle typen, mens Product Type Variant beskriver en definert variant.',concepts:['Product Type','Product Type Variant']},
        {difficulty:'medium',prompt:'Navigasjonssystemet er bare installert paa noen fartoy. Hvilket konsept angir hvilken struktur som faktisk gjelder for ASK2026;10?',options:['Applicability','SNS','PMTR','Logistic Pattern'],answer:0,explanation:'Applicability angir hvilke data eller strukturelementer som gjelder for et bestemt produkt eller en bestemt konfigurasjon.',concepts:['Applicability','Configuration']},
        {difficulty:'medium',prompt:'Hvorfor er en felles grunnstruktur med konfigurasjon ofte bedre enn en separat PBS for hvert av 20 fartoy?',options:['Den gjoer all konfigurasjon identisk','Den kan gjenbrukes mens definerte forskjeller uttrykkes per produkt','Den fjerner behovet for produktidentitet','Den skriver automatisk tekniske prosedyrer'],answer:1,explanation:'En gjenbrukbar struktur reduserer duplisering; applicability/configuration kan uttrykke variasjoner som faktisk finnes.',concepts:['PBS','Configuration','Applicability']},
        {difficulty:'hard',prompt:'En komponent finnes bare i Product Type Variant B, og ett konkret fartoy har variant A. Hva er tryggeste konklusjon?',options:['Komponenten gjelder for alle produkter fordi den finnes i grunnmodellen','Applicability maa avklare om komponenten gjelder for det konkrete produktet','En ny Article List gjoer komponenten universell','Produktets serienummer maa endres'],answer:1,explanation:'At en komponent finnes i en variant betyr ikke at den gjelder for alle konkrete produkter. Applicability avgrenser hva som gjelder.',concepts:['Product Type Variant','Product','Applicability']},
        {difficulty:'hard',prompt:'Leverandoeren endrer et system paa nye fartoy, men historiske fartoy skal beholde sin opprinnelige konfigurasjon. Hva maa modellen bevare?',options:['Bare siste Product Type','Produktidentitet og konfigurasjons-/applicability-kontekst over tid','Kun PDF av gammel PBS','Ett globalt Device Type Set uten produktkobling'],answer:1,explanation:'Historiske enheter maa kunne spores til sin konfigurasjon. En ny variant maa ikke utilsiktet endre hva som gjelder for allerede leverte produkter.',concepts:['Product','Configuration','Applicability']}
      ]
    },
    {
      id:'product-structure',title:'Product Structure',navTitle:'Product Structure',domain:'Struktur',duration:'9 min',
      goal:'Forstaa hvorfor Device Type, Article og Breakdown Element har ulike roller i PBS, og hvordan PBS skiller seg fra SNS og SBOM.',
      intro:'Produktstruktur beskriver hvordan produktet er satt sammen. Breakdown Element er en plass i strukturen; Device Type beskriver en type; Article inneholder konkret material-/partinformasjon. Strukturen kan starte foer endelig part number finnes.',
      example:'I ASK2026;10 legger vi inn Breakdown Element «Pump 01». Vi vet typen, men venter paa part number. Device Type kan representere pumpetypen inntil Article kan kobles til.',
      case:'ASK2026;10 trenger en hydraulisk pumpe foer leverandoeren har bestemt part number. Hvordan kan PBS bygges naa og kompletteres senere?',
      caseAnswer:'Opprett strukturelementet og modeller typen med Device Type. Naar part number finnes, kobles den konkrete Article-informasjonen til den relevante strukturen.',
      nodes:['product','pbs','breakdown','device-type','article','sns'],concepts:['Article','Article List','Device Type','Breakdown Element','PBS','SBOM','SNS'],
      questions:[
        {difficulty:'basic',prompt:'Pumpens part number er ikke kjent, men plassen i fartoyets struktur er klar. Hvilken kombinasjon lar modelleringen starte?',options:['Data Module og Info Code','Device Type og Breakdown Element','Article List og XSL','Product Type Variant og PMTR'],answer:1,explanation:'Breakdown Element oppretter strukturplassen, mens Device Type beskriver den kjente komponenttypen foer en konkret Article er tilgjengelig.',concepts:['Device Type','Breakdown Element']},
        {difficulty:'medium',prompt:'Part number PN-12345 blir levert for Pump 01. Hvilken rolle faar Article?',options:['Den beskriver produktstrukturen som helhet','Den inneholder konkret material-/partinformasjon som kan knyttes til strukturplassen','Den erstatter Product','Den er det samme som SNS'],answer:1,explanation:'Article representerer den konkrete material-/partinformasjonen. Breakdown Element fortsetter aa representere plassen i PBS.',concepts:['Article','Breakdown Element']},
        {difficulty:'medium',prompt:'Ingeniøren kaller Device Type og Article det samme fordi begge viser «pumpe». Hva er den viktige forskjellen?',options:['Device Type beskriver typen; Article beskriver konkret material-/partinformasjon','Article er alltid strukturplassen; Device Type er alltid PDF-en','Det finnes ingen forskjell','Device Type brukes bare i S1000D'],answer:0,explanation:'Typen kan vaere kjent foer endelig part number. Article identifiserer den konkrete materialinformasjonen naar den finnes.',concepts:['Device Type','Article']},
        {difficulty:'medium',prompt:'PBS viser den interne oppbygningen av fartoyet. SNS brukes for standardisert systemidentifikasjon. Hva boer du unngaa aa anta?',options:['At PBS og SNS maa vaere identiske tre-for-tre','At samme produkt kan ha struktur og systematisk identifikasjon','At komponenter har roller i produktet','At struktur kan inneholde flere nivaa'],answer:0,explanation:'PBS og SNS har ulike roller. SNS kan tildeles strukturen uten at intern PBS noedvendigvis er identisk med SNS-systemet.',concepts:['PBS','SNS']},
        {difficulty:'hard',prompt:'En felles komponenttype finnes i mange produktstrukturer, mens materialteamet vedlikeholder partnummeret. Hvordan reduseres duplisering?',options:['Opprett en Article-kopi for hvert Breakdown Element','Gjenbruk Article/Device Type som masterdata og knytt dem til relevante Breakdown Elements','Erstatt alle strukturplasser med SNS-koder','Flytt PBS inn i TechPub Project'],answer:1,explanation:'Skillet mellom masterobjekt og strukturplass lar samme informasjon gjenbrukes uten aa blande sammen identitet og plassering.',concepts:['Article','Device Type','Breakdown Element','Gjenbruk']},
        {difficulty:'hard',prompt:'En BOM-import inneholder flere varianter av samme komponent og skal brukes til reservedelsarbeid. Hvorfor kan Article Lists vaere nyttige?',options:['De definerer serienummeret paa hvert Product','De lar relevante Articles samles og styres som et utvalg uten aa forveksle listen med selve PBS','De erstatter alle Articles med en PDF','De bestemmer SNS automatisk'],answer:1,explanation:'Article List kan gruppere et relevant utvalg artikler for bruk. Den er ikke det samme som produktstrukturen eller de individuelle Article-objektene.',concepts:['Article List','Article','PBS']}
      ]
    },
    {
      id:'maintenance',title:'Maintenance',navTitle:'Maintenance',domain:'Vedlikehold',duration:'9 min',
      goal:'Se hvordan PBS og Maintenance Concept gir grunnlag for analyse og senere strukturerte vedlikeholdsoppgaver.',
      intro:'Vedlikehold tar utgangspunkt i produktet og dets struktur. Maintenance Concept beskriver hvordan produktet skal vedlikeholdes; MTA stoetter analyse/definisjon; Maintenance Task beskriver oppgaven med ressurser og intervaller.',
      example:'Pumpen i ASK2026;10 trenger planlagt inspeksjon. Analysen avklarer behovet, og Maintenance Task samler arbeidsinnhold, personell, utstyr, deler og tid.',
      case:'Fartoyets pumpe skal inspiseres hver 500 driftstime. Hvordan gaar du fra produktstruktur til gjenbrukbar vedlikeholdsinformasjon?',
      caseAnswer:'Knytt vedlikeholdsarbeidet til relevant struktur, analyser/definer oppgaven gjennom riktig vedlikeholdsarbeid, og modeller selve arbeidet som Maintenance Task med relevante ressurser og intervall.',
      nodes:['product','pbs','breakdown','mta','maintenance-task','analysis'],concepts:['Maintenance Concept','MTA','Maintenance Task','Maintenance Level','PMTR','Breakdown Element'],
      questions:[
        {difficulty:'basic',prompt:'Hva beskriver Maintenance Concept i et fartoyprosjekt?',options:['Hvilke metoder og nivaa vedlikeholdet er tenkt utført paa','Hvilket PDF-format brukes','Produktets serienummer','S1000D Info Code-listen'],answer:0,explanation:'Maintenance Concept beskriver hvordan produktet skal vedlikeholdes, inkludert planlagte vedlikeholdsnivaa.',concepts:['Maintenance Concept','Maintenance Level']},
        {difficulty:'medium',prompt:'Hvorfor er PBS relevant foer et team bygger vedlikeholdsoppgaver?',options:['PBS knytter oppgaven til produktdelen den gjelder for','PBS beregner automatisk intervall','PBS erstatter MTA','PBS publiserer Data Modules'],answer:0,explanation:'PBS gir den strukturelle konteksten for hvilke Breakdown Elements og produkter en vedlikeholdsoppgave gjelder.',concepts:['PBS','Maintenance Task']},
        {difficulty:'medium',prompt:'Et team analyserer behov og definerer vedlikeholdsarbeidet foer prosedyren skrives. Hvilket skille er viktig?',options:['MTA stotter analyse/definisjon; Maintenance Task beskriver den konkrete oppgaven','MTA er S1000D XML; Maintenance Task er PDF','MTA er en Article List; Maintenance Task er en Article','Det er samme objekt med to navn'],answer:0,explanation:'Analyse og oppgave har beslektede, men ulike roller. MTA brukes i analyse/definisjon; Maintenance Task representerer oppgaven.',concepts:['MTA','Maintenance Task']},
        {difficulty:'medium',prompt:'Vedlikeholdsoppgaven krever to teknikere, testutstyr, reservedel og 90 minutters arbeid. Hvorfor modellere dette strukturert?',options:['Ressurs- og tidsinformasjon kan brukes videre i stoetteanalyse og dokumentasjon','Det tvinger alle fartoy til samme bemanning','Det gjoer Article global','Det erstatter vedlikeholdskonseptet'],answer:0,explanation:'Strukturerte ressurser, deler og tidsforbruk kan analyseres og brukes videre, i stedet for aa bli liggende i en fritekstprosedyre.',concepts:['Maintenance Task','MTA']},
        {difficulty:'hard',prompt:'Et team skriver en prosedyre foer de har avklart hvilke produktvarianter og vedlikeholdsnivaa den gjelder for. Hva er risikoen?',options:['Prosedyren blir for enkel aa lese','Oppgaveinnhold kan bli koblet til feil struktur eller applicability og maa omarbeides','HICO sletter automatisk part number','SNS blir identisk med PBS'],answer:1,explanation:'Oppgaven maa knyttes til riktig produktstruktur og vedlikeholdskontekst. Avklar dette foer detaljert innhold for aa unngaa feil anvendelse.',concepts:['Maintenance Concept','PBS','Applicability','Maintenance Task']},
        {difficulty:'hard',prompt:'En strukturert Maintenance Task skal senere brukes som grunnlag for teknisk dokumentasjon. Hva maa vaere sant for at det skal vaere nyttig?',options:['Tasken maa inneholde relevant strukturert arbeid og relasjon til produkt/struktur','Tasken maa allerede vaere en ferdig PDF','Alle subtasker maa vaere Articles','Maintenance Concept maa vaere del av S1000D'],answer:0,explanation:'En strukturert oppgave med relevante koblinger og innhold gir et brukbart grunnlag videre. En PDF alene bevarer ikke modellens relasjoner.',concepts:['Maintenance Task','PBS','Data Module']}
      ]
    },
    {
      id:'analysis',title:'Analysis',navTitle:'Analysis',domain:'Analyse',duration:'8 min',
      goal:'Skille mellom analysemetoder, beslutningslogikk og forebyggende vedlikeholdskrav; forstaa hvordan resultatet kan spores.',
      intro:'Analyser begrunner og strukturerer beslutninger om stoette og vedlikehold. Decision Tree organiserer betingede sporsmaal og utfall; PMTR representerer et krav om forebyggende vedlikehold. De har ulike roller.',
      example:'En pumpe i ASK2026;10 viser risiko ved lang driftstid. Analyse vurderer svar og konsekvenser; et forebyggende krav kan deretter begrunne en planlagt Maintenance Task.',
      case:'Kunden vil vite hvorfor en pumpe inspiseres hver 500 timer. Hva hjelper med aa vise veien fra analyse til krav og oppgave?',
      caseAnswer:'Dokumenter relevant analyse og beslutningsgrunnlag. Decision Tree modellerer betingede vurderinger; PMTR uttrykker et forebyggende oppgavekrav; Maintenance Task beskriver selve arbeidet.',
      nodes:['analysis','decision-tree','pmtr','breakdown','maintenance-task'],concepts:['Decision Tree','PMTR','MTA','Maintenance Task'],
      questions:[
        {difficulty:'basic',prompt:'En analyse skal stille et sporsmaal, bruke svaret til aa velge neste vurdering og ende i et resultat. Hvilket objekt passer denne beslutningslogikken?',options:['Decision Tree','Article List','Data Module','Product Type Variant'],answer:0,explanation:'Decision Tree organiserer sporsmaal, svar, videre grener og resultater. Det er mer enn en flat liste med sporsmaal.',concepts:['Decision Tree']},
        {difficulty:'medium',prompt:'Et prosjekt har bestemt at et forebyggende vedlikeholdsarbeid maa opprettes. Hva uttrykker PMTR i denne sammenhengen?',options:['Et krav om aa opprette en preventive task','Den ferdige Data Module-filen','Det konkrete produktets serienummer','En Material Project-importlogg'],answer:0,explanation:'PMTR representerer et forebyggende vedlikeholdsoppgavekrav; det er ikke det samme som Decision Tree eller selve ferdige tasken.',concepts:['PMTR','Maintenance Task']},
        {difficulty:'medium',prompt:'Hvorfor er et Decision Tree nyttig naar en analyse gjelder et bestemt Breakdown Element?',options:['Det gir strukturert beslutningslogikk i konteksten til den aktuelle produktdelen','Det erstatter Breakdown Element med en Article','Det publiserer XML automatisk','Det setter alle fartoy til samme konfigurasjon'],answer:0,explanation:'Kobling til Breakdown Element forankrer analysen i den delstrukturen den gjelder for.',concepts:['Decision Tree','Breakdown Element']},
        {difficulty:'medium',prompt:'Samme analysetilnarming passer flere PSA Projects, men ett prosjekt har lokale endringer. Hva boer versjonsstyring beskytte?',options:['Originalen og sporbarheten for den prosjektspesifikke tilpasningen','At originalen overskrives uten historikk','At alle Decision Trees blir like','At prosjektet mister Breakdown Elements'],answer:0,explanation:'Versjoner lar teamet bevare opphav og se hva som er tilpasset, i stedet for aa skjule forskjellen ved aa overskrive originalen.',concepts:['Decision Tree','PSA Project']},
        {difficulty:'hard',prompt:'En ingeniør foreslaar en preventive task ut fra erfaring, men uten dokumentert analyse. Hva mangler for aa forklare hvorfor oppgaven finnes?',options:['Et sporbar begrunnelse som kobler analysekrav til den konkrete oppgaven','Et ekstra Product Type Variant','En ny TechPub Project for hvert spørsmål','En Article List med bare pumpen'],answer:0,explanation:'Oppgaven kan finnes, men uten analysegrunnlag er begrunnelsen vanskeligere aa etterprove. PMTR og relevant analyse kan gi denne sporbarheten.',concepts:['PMTR','Decision Tree','Maintenance Task']},
        {difficulty:'hard',prompt:'Et Decision Tree foreslaar inspeksjon bare ved et bestemt symptom. Hva maa bevares naar grenen ender i vedlikehold?',options:['Betingelsene, analyseutfallet og koblingen til relevant Maintenance Task','Bare sluttnoden som tekst','En global endring av alle Product Types','En Info Code som erstatter beslutningslogikken'],answer:0,explanation:'Sammenhengen mellom betingelse, svar, resultat og oppgave forklarer hvordan anbefalingen ble til og naar den gjelder.',concepts:['Decision Tree','Maintenance Task','Applicability']}
      ]
    },
    {
      id:'technical-publications',title:'Technical Publications',navTitle:'Technical Publications',domain:'Teknisk dokumentasjon',duration:'9 min',
      goal:'Forstaa hvordan vedlikeholdsdata blir knyttet til S1000D-dokumentasjon via TechPub Project, Info Codes, Logistic Pattern og Data Module.',
      intro:'Vedlikeholdsmodellen og teknisk publikasjon har ulike formaal. TechPub Project styrer publikasjonens regler; Info Code klassifiserer informasjonsinnhold; Logistic Pattern kan bygge bro fra logistikk-/vedlikeholdsdata til en Data Module.',
      example:'Pumpens Maintenance Task i ASK2026;10 skal brukes i en teknisk prosedyre. Modellen trenger riktig publikasjonssammenheng og kobling til Data Module Code.',
      case:'Vedlikeholdsoppgaven for pumpen maa kunne generere eller knyttes til en S1000D Data Module. Hvilke deler av modellen maa vurderes?',
      caseAnswer:'Se paa TechPub Project-regler, relevante Info Codes og Logistic Pattern, og koblingen fra Maintenance Task til Data Module Code/Data Module.',
      nodes:['maintenance-task','logistic-pattern','info-code','data-module','techpub'],concepts:['TechPub Project','Info Code','Logistic Pattern','Data Module','Data Module Code','S1000D'],
      questions:[
        {difficulty:'basic',prompt:'En Maintenance Task skal brukes som grunnlag i en teknisk publikasjon. Hvilket prosjektomraade styrer dokumentasjonsregler?',options:['TechPub Project','Material Project','Fleet','Product Type'],answer:0,explanation:'TechPub Project styrer regler for teknisk dokumentasjon, inkludert S1000D-relaterte prosjektinnstillinger.',concepts:['TechPub Project','S1000D']},
        {difficulty:'medium',prompt:'Hva er den viktigste rollen til Info Code i S1000D-sammenheng?',options:['A identifisere eller kategorisere typen teknisk informasjon','A angi fartoyets serienummer','A beskrive PBS-grenen','A erstatte alle Maintenance Tasks'],answer:0,explanation:'Info Code angir type informasjonsinnhold i teknisk dokumentasjon; den er ikke en produktidentitet eller vedlikeholdsoppgave.',concepts:['Info Code','S1000D']},
        {difficulty:'medium',prompt:'Hvorfor kan Logistic Pattern fungere som et bindeledd mellom Maintenance Task og publikasjon?',options:['Det kobler relevante logistikk-/vedlikeholdsbegreper til teknisk dokumentasjonsstruktur','Det konverterer automatisk enhver task til godkjent tekst','Det erstatter TechPub Project','Det er et part number-format'],answer:0,explanation:'Logistic Pattern knytter vedlikeholds-/LSA-siden til teknisk dokumentasjon og kan vaere med aa bestemme relevante Info Codes og Data Module-koblinger.',concepts:['Logistic Pattern','Maintenance Task','Info Code']},
        {difficulty:'medium',prompt:'En Logistic Pattern refererer til en Info Code som ikke finnes i TechPub Project. Hvorfor kan dette gi valideringsproblem?',options:['Prosjektets dokumentasjonsregler kjenner ikke den refererte koden','Info Code maa vaere et Product','PBS mangler et Fleet-objekt','En Maintenance Task kan bare ha ett trinn'],answer:0,explanation:'Pattern og prosjekt maa bruke kompatible Info Codes. Prosjektreglene gir konteksten som validerer referansene.',concepts:['Logistic Pattern','Info Code','TechPub Project']},
        {difficulty:'hard',prompt:'Samme Maintenance Task skal gjenbrukes, men ulike publikasjoner bruker ulike presentasjonsregler. Hva er en god separasjon?',options:['Behold taskens masterdata og styr publikasjonens regler og mapping i relevante TechPub-/Pattern-koblinger','Lag en egen kopi av tasken for hvert PDF-format','Flytt alle Info Codes inn i Article List','Bruk Applicability som erstatning for Data Module Code'],answer:0,explanation:'Oppgaveinnhold kan gjenbrukes, mens publikasjonsspesifikke regler og koblinger holdes i dokumentasjonslaget.',concepts:['Maintenance Task','TechPub Project','Logistic Pattern']},
        {difficulty:'hard',prompt:'Hvorfor er en Data Module mer enn en PDF-fil i denne flyten?',options:['Den er strukturert teknisk dokumentasjonsinformasjon som kan identifiseres og brukes modulært','Den er alltid en skannet tegning','Den inneholder bare materialpris','Den erstatter Product og PBS'],answer:0,explanation:'Data Module er en strukturert enhet av teknisk innhold. PDF kan vaere et output-format, men ikke hele den underliggende modellen.',concepts:['Data Module','S1000D','XSL']}
      ]
    },
    {
      id:'data-reuse',title:'Data & Reuse',navTitle:'Data & Reuse',domain:'Gjenbruk og datakvalitet',duration:'8 min',
      goal:'Forstaa hvordan Articles, Article Lists, importkontroll, validering og XSL kan stoette datakvalitet og gjenbruk.',
      intro:'Gjenbruk gjoer stor datamengde haandterbar, men oeker behovet for endringskontroll. Importlogg, Check Only, prosjektregler og validering synliggjoer hva som skjer foer data tas i bruk.',
      example:'Et leverandoerregneark inneholder tusenvis av Articles for ASK2026;10. Foer import kontrollerer teamet mapping, tester med Check Only og vurderer importloggen.',
      case:'Du har 10 000 Article-rader og er usikker paa mappingen. Hva er en forsvarlig foerste handling?',
      caseAnswer:'Kontroller mappingen og bruk Check Only for aa simulere hva importen vil endre. Gaa gjennom resultat/varsler foer faktisk import, og kontroller deretter loggen.',
      nodes:['article','article-list','material','import','validation','xsl'],concepts:['Article','Article List','Material Project','Data Quality','XSL','Project Rules'],
      questions:[
        {difficulty:'basic',prompt:'Et regneark med mange artikler skal importeres. Hva boer teamet gjoere foer det skriver endringer til masterdata?',options:['Kontrollere mapping og bruke Check Only for aa se forventede endringer','Overskrive alt og lese loggen senere','Fjerne alle project rules','Konvertere regnearket til PDF'],answer:0,explanation:'Check Only lar teamet simulere forventet effekt uten aa opprette eller endre data. Det gir en tryggere kontroll foer import.',concepts:['Check Only','Import','Data Quality']},
        {difficulty:'medium',prompt:'En Article List brukes av en Maintenance Task og flere TechPub-koblinger. Hvorfor krever endringer ekstra oppmerksomhet?',options:['Endringen kan paavirke alle stedene der listen brukes','Article Lists kan ikke endres','Bare tittelen kan oppdateres','En endring sletter alltid IPS Program'],answer:0,explanation:'Gjenbruk kan la endringer propagere til vedlikeholds- og dokumentasjonssammenhenger. Det er kraftig, men maa styres.',concepts:['Article List','Gjenbruk','Maintenance Task']},
        {difficulty:'medium',prompt:'Importloggen viser opprettet, oppdatert, hoppet over og feilet. Hva er dens viktigste verdi?',options:['Den gir sporbar oversikt over hva importen faktisk gjorde','Den godkjenner automatisk datakvaliteten','Den erstatter Article List','Den lager et nytt TechPub Project'],answer:0,explanation:'Loggen synliggjoer virkningen av importen og hjelper teamet med aa kontrollere avvik og oppfoelging.',concepts:['Import','Data Quality']},
        {difficulty:'medium',prompt:'Et team vil kontrollere store datamengder mot bestemte regler foer de brukes. Hvilke mekanismer er relevante?',options:['Validering, prosjektregler og eventuelt XSL-baserte kontroller','Bare Product Type Variant','Kun PDF-eksport','Applicability uten noen datakontroll'],answer:0,explanation:'Validering og prosjektregler kontrollerer at data foelger forventede rammer; XSL kan brukes til automatisert datakvalitetskontroll.',concepts:['Validation','Project Rules','XSL']},
        {difficulty:'hard',prompt:'Et Article List-utvalg brukes i vedlikehold og TechPubs. En bruker fjerner en artikkel for aa rydde i materialprosjektet. Hva maa vurderes foer endringen?',options:['Om fjerningen paavirker tasks og publikasjoner som gjenbruker listen','Om Product Type maa omdoepes','Om XSL kan legge artikkelen tilbake automatisk','Om SNS maa slettes fra alle fartoy'],answer:0,explanation:'En delt Article List kan ha nedstroemsbruk. Finn relasjonene og vurder konsekvensene foer du endrer masterutvalget.',concepts:['Article List','Gjenbruk','Data Quality']},
        {difficulty:'hard',prompt:'Check Only viser at en import vil tomme flere eksisterende attributter. Hva er beste neste steg?',options:['Stopp, undersoek mapping og importinnstillinger, og gjoer ingen faktisk import foer konsekvensen er forstaatt','Fortsett fordi Check Only ikke kan forutsi endringer','Slett alle Articles foerst','Ignorer varslet hvis radantallet stemmer'],answer:0,explanation:'Simuleringen avdekker en mulig destruktiv endring. Undersoek mapping/innstillinger og bekreft forventet resultat foer import.',concepts:['Check Only','Import','Project Rules']}
      ]
    },
    {
      id:'complete-case',title:'The Complete Case',navTitle:'Complete Case',domain:'Integrert case',duration:'10 min',
      goal:'Koble prosjekt, produkt, struktur, analyse, vedlikehold og teknisk dokumentasjon i en sammenhengende informasjonsflyt.',
      intro:'Naa introduseres faa nye begreper. Oppgaven er aa bruke den mentale modellen paa ett fartoy fra programnivaa til gjenbrukbar dokumentasjon og datakvalitet.',
      example:'ASK2026;10 leveres med subsystemer, komponenter med og uten part numbers, et vedlikeholdsprogram og teknisk dokumentasjon som skal kunne bygges paa vedlikeholdsdata.',
      case:'Du skal modellere ASK2026;10. For hvert steg velger du hvilket objekt eller prosjektlag som best viderefoerer informasjonsflyten.',
      caseAnswer:'IPS Program → Product → PBS/Breakdown Elements → Device Type foer part number → Article naar part number er kjent → analyse/MTA → Maintenance Task → TechPub Project/Info Code/Logistic Pattern/Data Module → Configuration/Applicability og kontrollert gjenbruk.',
      nodes:['ips','product','pbs','breakdown','device-type','article','analysis','maintenance-task','logistic-pattern','data-module','validation'],concepts:['IPS Program','Product','PBS','Device Type','Article','MTA','Maintenance Task','TechPub Project','Data Module','Applicability'],
      questions:[
        {difficulty:'basic',prompt:'Du starter et nytt fartoyprogram med flere arbeidsspor. Hvilket objekt gir den overordnede IPS-rammen?',options:['IPS Program','Product','Data Module','Article List'],answer:0,explanation:'IPS Program er overordnet ramme for relaterte analyse-, dokumentasjons- og materialprosjekter.',concepts:['IPS Program']},
        {difficulty:'medium',prompt:'ASK2026;10 er den konkrete enheten. Hvor representeres den?',options:['Product','Product Type','Device Type','Breakdown Element'],answer:0,explanation:'Product representerer den konkrete fysiske enheten. Product Type og Device Type beskriver generelle typer.',concepts:['Product','Product Type']},
        {difficulty:'medium',prompt:'Pumpeplassen skal inn i PBS, men endelig part number mangler. Hvilken kombinasjon lar arbeidet fortsette?',options:['Breakdown Element + Device Type','Data Module + Info Code','Article List + XSL','PMTR + Product Type Variant'],answer:0,explanation:'Breakdown Element gir strukturplassen; Device Type representerer den kjente typen foer Article er tilgjengelig.',concepts:['PBS','Breakdown Element','Device Type']},
        {difficulty:'medium',prompt:'Leverandoeren sender senere part number PN-12345. Hvilket objekt tilfører den konkrete material-/partinformasjonen?',options:['Article','Decision Tree','Applicability','SNS'],answer:0,explanation:'Article representerer den konkrete partinformasjonen og kan kobles til den eksisterende produktstrukturen.',concepts:['Article','Breakdown Element']},
        {difficulty:'hard',prompt:'Pumpeanalysen begrunner inspeksjon hver 500 timer, og samme vedlikeholdsdata skal senere brukes i publikasjon. Hvilken kjede bevarer mest faglig sammenheng?',options:['Analyse/PMTR → Maintenance Task → Logistic Pattern/Info Code → Data Module','Article List → Product Type → XSL → IPS Program','Product → PDF → SNS → Material Project','Decision Tree → Article → Fleet → Info Code'],answer:0,explanation:'Analysen begrunner oppgaven; Maintenance Task modellerer arbeidet; dokumentasjonskoblinger kan knytte det til Info Code og Data Module.',concepts:['PMTR','Maintenance Task','Logistic Pattern','Info Code','Data Module']},
        {difficulty:'hard',prompt:'20 fartoy deler grunnstruktur, men noen subsystemer varierer. Hvordan bevares gjenbruk uten aa late som alle er identiske?',options:['Gjenbruk grunnstrukturen, representer enhetene som Products og avgrens forskjeller med Configuration/Applicability','Opprett en enkelt Product og slett de andre serienumrene','Kopier alle Articles og Maintenance Tasks til 20 uavhengige databaser','Bruk Info Code som fartoyidentitet'],answer:0,explanation:'Gjenbrukbar struktur kombinert med produktidentitet og applicability lar variasjoner uttrykkes uten aa duplisere alt.',concepts:['Product','Configuration','Applicability','Gjenbruk']}
      ]
    }
  ],
  mapNodes: {
    hico:{label:'HICO INFORMATION MODEL', definition:'HICO modellerer objekter og relasjoner slik at produktstoetteinformasjon kan gjenbrukes og brukes videre.', module:1},
    sseries:{label:'S-SERIES STANDARDS', definition:'S-Series-standarder beskriver ulike fagomraader som kan moete i den sammenhengende HICO-modellen.', module:1},
    s1000d:{label:'S1000D', definition:'Standardomraadet for strukturert teknisk dokumentasjon.', module:2},
    s2000m:{label:'S2000M', definition:'Standardomraadet for material- og forsyningsinformasjon.', module:2},
    s3000l:{label:'S3000L', definition:'Standardomraadet for Logistics Support Analysis.', module:2},
    ips:{label:'IPS PROGRAM', definition:'Overordnet ramme for IPS-arbeid. Kan knytte sammen PSA, TechPub og material-/Article-arbeid.', module:2},
    psa:{label:'PSA PROJECT', definition:'Prosjektomraade for analyse, PBS og vedlikeholdsrelatert arbeid.', module:2},
    techpub:{label:'TECHPUB PROJECT', definition:'Prosjektomraade for regler og struktur knyttet til teknisk dokumentasjon.', module:2},
    material:{label:'MATERIAL / ARTICLE DATA', definition:'Omraade for materialinformasjon og Articles som kan gjenbrukes i struktur og stoettearbeid.', module:2},
    product:{label:'PRODUCT', definition:'Den konkrete fysiske enheten, for eksempel ASK2026;10.', module:3},
    'product-type':{label:'PRODUCT TYPE / VARIANT', definition:'Beskriver felles produkttype og definerte varianter.', module:3},
    applicability:{label:'CONFIGURATION / APPLICABILITY', definition:'Angir hvordan variasjoner modelleres og hvilke data som gjelder for et bestemt produkt.', module:3},
    pbs:{label:'PRODUCT STRUCTURE / PBS', definition:'Produktets strukturelle oppbygning.', module:4},
    breakdown:{label:'BREAKDOWN ELEMENT', definition:'En bestemt plass eller et element i produktstrukturen.', module:4},
    'device-type':{label:'DEVICE TYPE', definition:'Beskriver komponenttypen foer en konkret Article/part number er tilgjengelig.', module:4},
    article:{label:'ARTICLE', definition:'Konkret material-/partinformasjon som kan knyttes til strukturen.', module:4},
    'article-list':{label:'ARTICLE LIST', definition:'Et valgt eller gruppert utvalg Articles som kan brukes i flere arbeidsomraader.', module:8},
    sns:{label:'SNS', definition:'Standardisert systemidentifikasjon; trenger ikke vaere identisk med intern PBS.', module:4},
    mta:{label:'MTA', definition:'Analyse-/definisjonsarbeid for vedlikeholdsoppgaver.', module:5},
    'maintenance-task':{label:'MAINTENANCE TASK', definition:'Strukturert beskrivelse av det konkrete vedlikeholdsarbeidet.', module:5},
    'maintenance-concept':{label:'MAINTENANCE CONCEPT', definition:'Beskriver hvordan produktet skal vedlikeholdes og paa hvilke nivaa.', module:5},
    'maintenance-level':{label:'MAINTENANCE LEVEL', definition:'Nivaaet der en vedlikeholdsoppgave er planlagt utfoert.', module:5},
    analysis:{label:'ANALYSIS / DECISION TREE', definition:'Strukturert vurdering og beslutningslogikk som kan begrunne stoettebehov.', module:6},
    'decision-tree':{label:'DECISION TREE', definition:'Beslutningslogikk med sporsmaal, svar, grener og resultat.', module:6},
    pmtr:{label:'PMTR', definition:'Preventive Maintenance Task Requirement: et krav om en forebyggende oppgave.', module:6},
    'logistic-pattern':{label:'LOGISTIC PATTERN', definition:'Et bindeledd mellom logistikk-/vedlikeholdsdata og teknisk dokumentasjon.', module:7},
    'info-code':{label:'INFO CODE', definition:'Identifiserer/kategoriserer type teknisk informasjon i S1000D-sammenheng.', module:7},
    'data-module':{label:'DATA MODULE', definition:'En modulær enhet av strukturert teknisk dokumentasjonsinnhold.', module:7},
    validation:{label:'VALIDATION / OUTPUT', definition:'Kontrollert validering, datakvalitet og videre bruk av informasjon.', module:8},
    import:{label:'IMPORT / LOG FILE', definition:'Kontrollert innlasting av data med en logg over hva som ble opprettet, oppdatert eller hoppet over.', module:8}
  },
  glossary: [
    ['HICO','System for aa modellere og koble produktstoette- og teknisk dokumentasjonsinformasjon.','Brukes gjennom informasjonsmodellen.','IPS Program, PSA Project, Product, Article'],
    ['ILS','Integrated Logistics Support: et begrep for integrert logistikkstoette.','Brukes naar stoettebehov sees samlet.','IPS, S-Series'],
    ['IPS','Integrated Product Support: stoette gjennom produktets levetid.','Overordnet stoette- og analyseomraade.','IPS Program, PSA Project'],
    ['S-Series','Familie av standarder for ulike IPS- og dokumentasjonsomraader.','Hvilken type fagproblem en standard adresserer.','S1000D, S2000M, S3000L'],
    ['S1000D','Standard for strukturert teknisk dokumentasjon.','TechPub Project og Data Modules.','Info Code, Data Module, Logistic Pattern'],
    ['S2000M','S-Series-omraade for material- og forsyningsinformasjon.','Reservedels-/materialarbeid.','Article, Material Project'],
    ['S3000L','S-Series-omraade for Logistics Support Analysis.','Stoette- og vedlikeholdsanalyse.','PSA Project, MTA, Maintenance Task'],
    ['ASD','Organisasjonen bak S-Series-standardene.','Hver spesifikasjon har egen industrikomité som utvikler faginnholdet.','S-Series, S1000D, S2000M, S3000L'],
    ['IPS Program','Overordnet prosjekt-/programramme for IPS-arbeid.','Kan samle flere fagprosjekter.','PSA Project, TechPub Project, Material Project'],
    ['PSA Project','Prosjektomraade for Product Support Analysis.','PBS og vedlikeholdsrelatert analyse.','IPS Program, PBS, MTA'],
    ['TechPub Project','Prosjektomraade for tekniske publikasjoner og dokumentasjonsregler.','S1000D-relatert prosjektarbeid.','Info Code, Data Module'],
    ['Material Project','Prosjektomraade for materialinformasjon.','Organisering av Articles og Article Lists.','Article, Article List'],
    ['Product','En konkret fysisk enhet, som ASK2026;10.','En bestemt levert/konfigurert enhet.','Product Type, Configuration, Applicability'],
    ['Product Type','En generell type produkt.','Beskriver felles egenskaper foer konkrete enheter.','Product Type Variant, Product'],
    ['Product Type Variant','En definert variant av en produkttype.','Beskriver produktforskjeller.','Product Type, Configuration'],
    ['Fleet','En gruppe relaterte produkter/enheter.','Oversikt over flere konkrete Products.','Product, Applicability'],
    ['Configuration','Beskrivelse av hvordan en konkret enhet er satt sammen.','Haandterer variasjoner fra grunnstruktur.','Product, Applicability, PBS'],
    ['Applicability','Angir hvilke data eller strukturer som gjelder for et produkt.','Avgrenser produktvariasjoner.','Product, Configuration, PBS'],
    ['Article','Objekt for konkret material-/partinformasjon.','Kan knyttes inn i produktstruktur.','Breakdown Element, Article List'],
    ['Article List','Et valgt eller gruppert utvalg Articles.','Material Project og nedstroemsbruk.','Article, Maintenance Task, TechPub'],
    ['Device Type','En modell av en type komponent/enhet.','Nyttig foer endelig Article finnes.','Breakdown Element, Article'],
    ['Breakdown Element','Et element/plass i produktstrukturen.','PBS og kobling til type eller Article.','PBS, Device Type, Article, Maintenance Task'],
    ['PBS','Product Breakdown Structure: produktets interne struktur.','Bygger opp produktets subsystemer og komponenter.','Product, Breakdown Element, Maintenance Task'],
    ['Product Structure','Produktets gjenbrukbare struktur, opprettet på IPS Program-nivå før PSA Project bruker den.','Product Code identifiserer strukturmodellen; et Product er den konkrete fysiske leveransen.','IPS Program, PSA Project, PBS, Product'],
    ['SBOM','Software Bill of Materials: oversikt over programvarekomponenter.','Programvareinnhold i produktet.','Product, Configuration'],
    ['SNS','Standard Numbering System for systematisk identifikasjon.','Kan tilordnes strukturen; trenger ikke vaere PBS.','PBS, Data Module Code'],
    ['Maintenance Concept','Beskriver hvordan produktet skal vedlikeholdes.','Planlegging av vedlikeholdsnivaa og tilnaerming.','MTA, Maintenance Level, Maintenance Task'],
    ['MTA','Maintenance Task Analysis: analyse/definisjonsarbeid for oppgaver.','Utvikling av vedlikeholdsbehov.','PBS, Breakdown Element, Maintenance Task'],
    ['Maintenance Task','Strukturert beskrivelse av konkret vedlikeholdsarbeid.','Utfors, analyseres og kan danne grunnlag for dokumentasjon.','MTA, Breakdown Element, Data Module'],
    ['Maintenance Level','Nivaaet der vedlikehold skal utføres.','Maintenance Concept og planlegging.','Maintenance Task, Maintenance Concept'],
    ['Decision Tree','Beslutningslogikk med sporsmaal, svar, grener og resultat.','Analyse av produktstoette og vedlikehold.','Breakdown Element, Maintenance Task'],
    ['PMTR','Preventive Maintenance Task Requirement: krav om forebyggende oppgave.','Forebyggende vedlikeholdsanalyse.','Decision Tree, Maintenance Task'],
    ['Info Code','Kategorisering av type teknisk informasjon i S1000D.','TechPub Project og dokumentasjonskoblinger.','Logistic Pattern, Data Module'],
    ['Logistic Pattern','Mønster som knytter logistikk-/vedlikeholdsdata til teknisk dokumentasjon.','Overgang mellom S3000L- og S1000D-relatert arbeid.','Maintenance Task, Info Code, Data Module'],
    ['Data Module','Modulaer enhet av strukturert teknisk dokumentasjonsinnhold.','Teknisk publikasjon; mer enn en PDF-eksport.','S1000D, Info Code, Maintenance Task'],
    ['Data Module Code','Kode som identifiserer en Data Module etter relevante regler.','S1000D-innhold og koblinger fra vedlikehold.','SNS, Info Code, Logistic Pattern'],
    ['XSL','Transformasjonsteknologi for strukturert data til ulike output-formater.','Publisering og automatisert datakvalitetskontroll.','Data Module, Validation'],
    ['Data Quality','Kontroll av at data er gyldige, komplette og konsistente for tiltenkt bruk.','Import, prosjektregler og validering.','XSL, Project Rules, Import'],
    ['Project Rules','Prosjektregler som rammer inn forventede data og referanser.','Kontroll og validering i prosjekt.','TechPub Project, Validation, Info Code'],
    ['Security Classification','Klassifisering som inngår i TechPub-konfigurasjonen.','TechPub Project trenger minst én konfigurert klassifisering før dokumentasjonsoppsettet tas i bruk.','TechPub Project, Data Module'],
    ['Check Only','Importkontroll som simulerer effekt uten aa opprette eller endre data.','Kontroller mapping foer import.','Import, Log File, Data Quality'],
    ['Import Log','Sporbar oversikt over opprettede, oppdaterte, hoppede over eller feilede rader.','Kontroll av store dataimporter.','Article, Check Only, Data Quality']
  ],
  handbookFacts: [
    {term:'ASD',aliases:['ASD','spesifikasjonene','komiteer'],modules:[1],text:'ASD står bak S-Series-standardene. De enkelte spesifikasjonene har egne komiteer med representanter fra industrien.',source:'ASD og S-Series'},
    {term:'S-Series',aliases:['S-Series','S1000D','S2000M','S3000L','S4000P','S5000F'],modules:[1],text:'S-Series-standardene dekker ulike fagområder: S2000M material og forsyning, S3000L logistikkstøtteanalyse og vedlikeholdsrelatert analyse, S4000P preventive maintenance og S1000D teknisk dokumentasjon.',source:'Oppslagsverket · ASD og S-Series'},
    {term:'HICO',aliases:['HICO','database','arbeidsplattform','gjenbruk','sentrale HICO-data'],modules:[1],text:'HICO modellerer og kobler produkt-, logistikk-, vedlikeholds- og dokumentasjonsdata. Objekter kan gjenbrukes på tvers av relevante produkter og prosjekter.',source:'Oppslagsverket · HICO på 30 sekunder'},
    {term:'Kundekonfigurasjon',aliases:['kundespesifikk','kunden','output','XSLT','XSL','maler','automatisering','mapping'],modules:[1],text:'Kundetilpasning kan håndteres med prosjektkonfigurasjon, oppdateringer, XSL/XSLT, maler og automatisering uten nødvendigvis å endre den generelle HICO-modellen. Avklar ønsket output før template-mapping endres.',source:'Oppslagsverket · Project Rules og XSL'},
    {term:'Bulk-import',aliases:['import','datamengden','bulk','mange data','10 000','regneark','BOM'],modules:[1,3],text:'HICO kan starte med manuell opprettelse og senere bruke prosesser og bulk-import når datamengden øker. Kontroller objekter, mapping, struktur, regler og koblinger før import.',source:'Oppslagsverket · Data Quality og oppstart'},
    {term:'Prosjektstandarder',aliases:['standarder','SFI','SNS','S1000D-versjon','S1000D','standardversjon'],modules:[1],text:'Avklar kundens eksisterende SFI/SNS og S-Series-standarder før prosjektet konfigureres, fordi de påvirker produktstruktur, identifikasjon og dokumentasjon.',source:'Oppslagsverket · SFI, SNS og LCN'},
    {term:'SFI',aliases:['SFI','systemidentifikasjon'],modules:[1,2],text:'SFI brukes som standardisert systemidentifikasjon. SFI, SNS og LCN har ulike roller og bør ikke behandles som synonymer.',source:'Oppslagsverket · SFI, SNS og LCN'},
    {term:'IPS Program',aliases:['IPS Program','programnivå','overordnede nivået','overordnet program','paraply'],modules:[1],text:'IPS Program er den overordnede rammen. Den kan samle flere PSA Projects og koblinger til TechPub Project og Material Project.',source:'Oppslagsverket · IPS Program'},
    {term:'PSA Project',aliases:['PSA Project','PSA Projects','PSA-arbeidet','PSA-prosjekt','ett PSA Project','PSA Project må','PSA-prosjekter'],modules:[1],text:'PSA Project ligger under et IPS Program og brukes blant annet for PBS, S3000L-data, analyser og Maintenance Tasks. I oppslagsverkets oppsett knyttes det til relevant struktur og prosjektgrunnlag.',source:'Oppslagsverket · PSA Project'},
    {term:'PSA-avhengigheter',aliases:['grunnkonfigurasjon','godkjenning','godkjennes','nødvendige koblinger','koblet til IPS Program'],modules:[1],text:'Et PSA Project må ligge under et IPS Program; manglende obligatoriske prosjektkoblinger eller regler kan hindre godkjenning. Oppslagsverket nevner blant annet relevante TechPub- og Material-koblinger.',source:'Oppslagsverket · Hvorfor kan et PSA Project ikke bare opprettes og brukes?'},
    {term:'Project Rules',aliases:['Project Rules','forretningsregler','beslutningspunkter','regler','Product Code'],modules:[1],text:'Project Rules er prosjektets konfigurerte forretningsregler og beslutningspunkter. Skill mellom regler, konfigurasjonsverdier og dataene som produseres.',source:'Oppslagsverket · Project Rules'},
    {term:'Product Structure',aliases:['Product Structure','Product Code','IPS Program-nivå','Product Structures'],modules:[1,2],text:'Product Structure/PBS opprettes på IPS Program-nivå før PSA Project bruker den. Oppslagsverket fremhever navn og Product Code som strukturens sentrale identifikasjon.',source:'Oppslagsverket · PBS og prosjektoppsett'},
    {term:'TechPub Project',aliases:['TechPub Project','TechPub','Technical Publications','S1000D-regler'],modules:[1,3],text:'TechPub Project styrer grunnlaget og reglene for teknisk dokumentasjon, blant annet S1000D-versjon, språk, SNS, Info Codes, Template og Schema.',source:'Oppslagsverket · TechPub Project'},
    {term:'Material Project',aliases:['Material Project','Material Projects','materialprosjekt'],modules:[1],text:'Material Project er prosjektspesifikt og kan samle relevante Article Lists. Articles er sentrale databaseobjekter og kan gjenbrukes; prosjektet er ikke en separat Article-database.',source:'Oppslagsverket · Material Project'},
    {term:'Article',aliases:['Article','Articles','part number','partnummer','OEM','leverandørnummer','OEM Article'],modules:[2,3],text:'Article representerer konkret material-/partinformasjon. En Article kan gjenbrukes på tvers av relevante strukturer og prosjekter; eget part number og OEM-nummer kan modelleres som separate Articles som kobles sammen.',source:'Oppslagsverket · Article og OEM Article'},
    {term:'Device Type',aliases:['Device Type','Device Types','typen','type før','før den endelige Article','part number ikke'],modules:[2],text:'Device Type beskriver hva slags enhet det er, og er nyttig før endelig part number eller Article finnes. Den kan knyttes til et Breakdown Element slik at PBS bygges tidlig.',source:'Oppslagsverket · Article, Device Type og Breakdown Element'},
    {term:'Breakdown Element',aliases:['Breakdown Element','Breakdown Elements','PBS-linje','PBS-element','element/linje'],modules:[2],text:'Breakdown Element er en plass eller linje i PBS-en. Det angir hvor en komponent hører hjemme; Device Type beskriver typen og Article den konkrete delen.',source:'Oppslagsverket · Breakdown Element'},
    {term:'PBS',aliases:['PBS','Product Structure','produktstrukturen','produktstruktur','BOM','strukturen'],modules:[2],text:'PBS beskriver produktets logiske oppbygning. Den gir vedlikeholdsoppgaver kontekst om hvor i produktet arbeidet hører hjemme, og kan bygges før alle Articles er kjent.',source:'Oppslagsverket · PBS'},
    {term:'SNS',aliases:['SNS','SFI','standardisert struktur','system-/funksjonsidentifikasjon'],modules:[2],text:'SNS er standardisert system-/funksjonsidentifikasjon og nummerering. Det beskriver ikke nødvendigvis den interne PBS-en; prosjektet kan ha egen PBS-logikk.',source:'Oppslagsverket · SFI, SNS og LCN'},
    {term:'LCN',aliases:['LCN','nummerering','Product Code','plassering i produktstrukturen'],modules:[2],text:'LCN brukes i logistikk-/vedlikeholdssammenheng for å identifisere plassering i produktstrukturen. Nummereringen kan genereres ut fra PBS.',source:'Oppslagsverket · SFI, SNS og LCN'},
    {term:'Article List',aliases:['Article List','Article Lists','liste over Articles','gruppert samling'],modules:[2,3],text:'Article List er et valgt eller gruppert utvalg av Articles, ikke selve artikkelen eller PBS-en. Delte lister kan brukes flere steder, så endringer må vurderes mot nedstrømsbruk.',source:'Oppslagsverket · Article List'},
    {term:'Source',aliases:['Source','Sources','Source Content Type','kildedokumentasjon','datasheet','3D Model'],modules:[2,3],text:'Source representerer kildedokumentasjon som tegning, datasheet eller 3D-modell. Den kan kobles til Article, Device Type, Breakdown Element eller Maintenance Task for å vise hvor informasjonen kommer fra.',source:'Oppslagsverket · Source'},
    {term:'Product',aliases:['Product','Products','fysiske Products','fysiske enheten','leveranse','serialiserte enheten'],modules:[2],text:'Product er den konkrete fysiske leveransen. Product Type beskriver den generelle typen; Fleet samler Products, og Product følger den konkrete leveransen gjennom livsløpet.',source:'Oppslagsverket · Product er ikke det samme som PBS'},
    {term:'Product Type Variant',aliases:['Product Type Variant','Product Type Variants','Variant','konfigurasjonsalternativ','Automation','Navigation','DP'],modules:[2],text:'Product Type Variant er et gjenbrukbart konfigurasjonsnivå under Product Type. Det beskriver alternativer før de konkrete Product-instansene opprettes.',source:'Oppslagsverket · Product Type → Product Type Variant → Product'},
    {term:'Fleet',aliases:['Fleet','Fleets','kundegruppe','samling Products'],modules:[2],text:'Fleet er en samling av Products, for eksempel produkter som hører til samme kunde. Product er fortsatt den enkelte fysiske leveransen.',source:'Oppslagsverket · Product Type og Product'},
    {term:'Applicability',aliases:['Applicability','gjelder for et bestemt Product','hvilket Product','ulik Data Module','filtreres ved publisering'],modules:[2,3],text:'Applicability angir hvilke struktur- eller dokumentasjonsdata som gjelder for et bestemt Product. Den lar en gjenbrukt struktur eller Data Module filtreres til riktig konfigurasjon.',source:'Oppslagsverket · Configuration Management og Applicability'},
    {term:'Configuration Management',aliases:['Configuration Management','samme PBS','mange fartøy','flere fysiske Products','konfigurasjonsstyring'],modules:[1,2],text:'Configuration Management og Applicability lar flere konkrete Products gjenbruke en grunnstruktur samtidig som forskjeller mellom leveransene angis.',source:'Oppslagsverket · Configuration Management'},
    {term:'MTA',aliases:['MTA','Maintenance Task Analysis','analysearbeid','analysen'],modules:[3],text:'MTA er Maintenance Task Analysis: analysearbeid som identifiserer og definerer nødvendig vedlikehold ut fra produktstrukturen.',source:'Oppslagsverket · MTA'},
    {term:'Maintenance Task',aliases:['Maintenance Task','Maintenance Tasks','task','oppgave','hovedtask','Supporting Task','Rectifying Task','Corrective Task','Preventive Task'],modules:[3],text:'Maintenance Task er den konkrete, strukturerte vedlikeholdsoppgaven. Den kan inneholde ressurser, personell, materiell, betingelser, handlinger og intervall, og knyttes til relevant produktstruktur.',source:'Oppslagsverket · Maintenance Task'},
    {term:'Maintenance Concept',aliases:['Maintenance Concept','vedlikeholdsnivå','vedlikeholdskonsept'],modules:[3],text:'Maintenance Concept beskriver den overordnede tankegangen for hvordan produktet skal vedlikeholdes, på hvilke nivåer og med hvilke typer oppgaver.',source:'Oppslagsverket · Maintenance Concept'},
    {term:'Maintenance Level',aliases:['Maintenance Levels','Maintenance Level','nivåene','rekkefølgen','mange tasks refererer'],modules:[3],text:'Maintenance Levels angir hvor vedlikehold utføres. Oppslagsverket anbefaler å planlegge nivåene tidlig fordi rekkefølgen kan være vanskelig å endre når mange Tasks refererer til dem.',source:'Oppslagsverket · Maintenance Levels'},
    {term:'Supporting Task',aliases:['Supporting Task','Supporting Tasks','Rectifying Task','hjelpeoppgave','støtter gjennomføringen'],modules:[3],text:'Supporting Task støtter gjennomføringen av en annen Task; Rectifying/Corrective Task utfører eller korrigerer selve vedlikeholdsaktiviteten. By-reference gjør at støtteaktiviteten kan gjenbrukes.',source:'Oppslagsverket · Supporting Task'},
    {term:'Preventive Task og Intervals',aliases:['Preventive Task','Preventive Tasks','interval','intervall','500 driftstimer','arbeid/bruk','event'],modules:[3],text:'Preventive Task skal ha et definert intervall, for eksempel tid, drift/bruk eller en relevant event. Intervallet er et kriterium for når oppgaven utføres.',source:'Oppslagsverket · Preventive Task og Intervals'},
    {term:'Decision Tree',aliases:['Decision Tree','spørsmål/svar','analyse basert på','beslutningslogikk'],modules:[3],text:'Decision Tree strukturerer spørsmål, svar, grener og resultat. Det dokumenterer hvordan en analyse kom fram til et vedlikeholdsbehov.',source:'Oppslagsverket · Decision Tree'},
    {term:'PMTR',aliases:['PMTR','Preventive Maintenance Task Requirement','forebyggende vedlikeholdskrav'],modules:[3],text:'PMTR er et krav om å etablere en Preventive Maintenance Task. Det er et krav/grunnlag, ikke selve Maintenance Task-en.',source:'Oppslagsverket · PMTR'},
    {term:'Data Module',aliases:['Data Module','Data Modules','Issue','Work','S1000D Data Module'],modules:[3],text:'Data Module er en S1000D-basert teknisk informasjonsenhet, ikke synonymt med Maintenance Task eller en PDF. Work er ikke-frigitt endring; Issue er frigitt versjon.',source:'Oppslagsverket · Maintenance Task vs. Data Module og Issue/Work'},
    {term:'Info Code',aliases:['Info Code','Info Codes','Info Code-numre'],modules:[3],text:'Info Code identifiserer type teknisk informasjon. Kodene kommer fra valgt S1000D-versjon og må være tilgjengelige i TechPub Project før en Logistic Pattern kan bruke dem.',source:'Oppslagsverket · Info Code'},
    {term:'Logistic Pattern',aliases:['Logistic Pattern','Logistic Patterns','mapping','PSA/LSA-språk','TechPub-språk','filter'],modules:[1,3],text:'Logistic Pattern mapper relevante S1000D Info Codes til et prosjektspesifikt PSA/LSA-språk. Det er bindeleddet mellom vedlikeholdsanalysen og TechPub, ikke en PBS eller produktliste.',source:'Oppslagsverket · Logistic Pattern'},
    {term:'TechPub Configuration',aliases:['S1000D-versjonen','S1000D-versjon','Model Identification','Template','Schema','Link Set','Blacklist','Security Classification','Language'],modules:[1,3],text:'TechPub Project må ha riktig S1000D-versjon og relevante regler, blant annet Info Codes, Template, Schema, Link Set, språk og minst én Security Classification før dokumentasjonen kan valideres.',source:'Oppslagsverket · TechPub Project'},
    {term:'Schema og Template',aliases:['Schema','Data Module Template','Template','XML-struktur','XML-strukturen'],modules:[3],text:'Template definerer hvilken XML-struktur en Data Module kan bruke; Schema validerer at XML-innholdet følger denne strukturen.',source:'Oppslagsverket · Template og Schema'},
    {term:'Link Set',aliases:['Link Set','kobles til HICO-objekter','S1000D-relasjon'],modules:[3],text:'Link Set styrer hvordan koblinger håndteres i den valgte S1000D-versjonen. En kobling etablerer både en S1000D-relasjon og en databasekobling.',source:'Oppslagsverket · Link Set'},
    {term:'Source Content Type',aliases:['Source Content Type','klassifisering','filtrere og finne'],modules:[2,3],text:'Source Content Type klassifiserer kildeinnhold, for eksempel som 3D Model. Klassifisering gjør det enklere å filtrere og finne kildedokumentasjon.',source:'Oppslagsverket · Source'},
    {term:'XSL og Data Quality',aliases:['XSL','XSLT','output','transformasjon','eksport','datakvalitet','XSL-template'],modules:[1,3],text:'XSL/XSLT kan transformere, trekke ut og kontrollere strukturerte data. Behold originaltemplate; tilpass en kopi og valider mapping mot ønsket output.',source:'Oppslagsverket · Data Quality og XSL'},
    {term:'Article-revisjon',aliases:['revisjon','Issue','samme part number','nytt part number','overskrives'],modules:[2,3],text:'Et nytt part number opprettes som en ny Article. Endret informasjon for samme part number kan håndteres gjennom revisjon/Issue slik at historikken beholdes.',source:'Oppslagsverket · Revision og endringer'},
    {term:'Import og Check Only',aliases:['Check Only','import','mapping','tom me','overskrive','bulk-import','import-logg','Import Log'],modules:[1,3],text:'Check Only simulerer import uten å endre data. Kontroller mapping og forventede endringer først, og bruk importloggen etterpå for å se hva som ble opprettet, oppdatert eller hoppet over.',source:'Oppslagsverket · Data Quality og import'},
    {term:'Security Classification',aliases:['Security Classification','klassifisering før TechPub','minst én Security Classification'],modules:[1,3],text:'TechPub Project må ha minst én Security Classification konfigurert før dokumentasjonsoppsettet kan brukes.',source:'Oppslagsverket · Security Classification'},
    {term:'Product Code',aliases:['Product Code','navn og Product Code'],modules:[1,2],text:'Product Structure identifiseres med navn og Product Code. Product Code er strukturens identifikator, ikke serienummeret til en fysisk Product.',source:'Oppslagsverket · PBS og prosjektoppsett'},
    {term:'PSA Project og én PBS',aliases:['én PBS','ny PBS','flere PSA Projects','flere Projects'],modules:[1],text:'I den beskrevne oppsettmodellen er PSA Project knyttet til én PBS. Ulike hovedområder som trenger hver sin PBS kan organiseres i separate PSA Projects under samme IPS Program.',source:'Oppslagsverket · PSA Project og PBS'},
    {term:'ASD',aliases:['ASD','komiteer','organisasjon bak spesifikasjonene'],modules:[1],text:'ASD er organisasjonen bak S-Series-standardene. De enkelte spesifikasjonene har egne komiteer med representanter fra industrien.',source:'Oppslagsverket · ASD og S-Series'}
  ],
  relationships: [
    {a:'Article',b:'Breakdown Element',label:'kobles inn i produktstrukturen',detail:'Article representerer konkret material-/partinformasjon. Breakdown Element representerer plassen i PBS. Naar part number finnes, kan Article knyttes til riktig strukturplass.'},
    {a:'PBS',b:'Maintenance Task',label:'forankrer vedlikehold',detail:'PBS viser produktets oppbygning. Maintenance Task knyttes til relevant produktdel slik at vedlikeholdsarbeidet har en tydelig kontekst.'},
    {a:'Maintenance Task',b:'Data Module',label:'foerer vedlikeholdsdata til publikasjon',detail:'Maintenance Task beskriver arbeidet. Relevant TechPub Project, Logistic Pattern, Info Code og Data Module-kobling knytter vedlikeholdsmodellen til teknisk dokumentasjon.'},
    {a:'Info Code',b:'Logistic Pattern',label:'klassifiserer dokumentasjonskobling',detail:'Logistic Pattern kan bruke Info Codes som finnes i TechPub Project for aa beskrive relevant teknisk innhold.'},
    {a:'Product',b:'Applicability',label:'avgrenser hva som gjelder',detail:'Product er den konkrete enheten. Applicability uttrykker hvilke struktur- og stoettedata som gjelder for den enheten.'},
    {a:'Device Type',b:'Breakdown Element',label:'bygger struktur foer part number finnes',detail:'Device Type beskriver komponenttypen; Breakdown Element gir den en plass i produktstrukturen foer en konkret Article er tilgjengelig.'},
    {a:'IPS Program',b:'PSA Project',label:'organiserer analysearbeid',detail:'IPS Program er overordnet ramme. PSA Project organiserer PBS og vedlikeholdsrelatert analyse.'},
    {a:'Article',b:'Article List',label:'grupperer gjenbrukbare Articles',detail:'Article List samler et valgt utvalg Articles. Endringer i en gjenbrukt liste maa kontrolleres fordi flere arbeidsomraader kan bruke den.'}
  ]
};

const norwegianWordCorrections = {
  analyseomraade:'analyseområde', arbeidsomraader:'arbeidsområder', arbeidsomraadet:'arbeidsområdet',
  arkitekturforstaaelse:'arkitekturforståelse', boer:'bør', dataomraader:'dataområder', dokumentasjonsomraader:'dokumentasjonsområder',
  foelger:'følger', foerer:'fører', foerst:'først', foerste:'første', forstaa:'forstå', forstaaelse:'forståelse', forstaatt:'forstått',
  foer:'før', Foer:'Før', foreslaar:'foreslår', formaal:'formål', Gaa:'Gå', gjoer:'gjør', gjoere:'gjøre', haandterbar:'håndterbar', haandtere:'håndtere', Haandterer:'Håndterer', haandterer:'håndterer',
  hoere:'høre', hoerer:'hører', leverandoeren:'leverandøren', Leverandoeren:'Leverandøren', leverandoerregneark:'leverandørregneark',
  laere:'lære', moete:'møte', Modulaer:'Modulær', nedstroemsbruk:'nedstrømsbruk', noedvendigvis:'nødvendigvis', oeker:'øker', omdoepes:'omdøpes',
  Omraade:'Område', omraade:'område', omraadet:'området', omraadene:'områdene', oppfoelging:'oppfølging', paavirke:'påvirke',
  paavirker:'påvirker', paavirkes:'påvirkes', paavirket:'påvirket', spoer:'spør', sporsmaal:'spørsmål', tilnaerming:'tilnærming',
  stoette:'støtte', stoetteanalyse:'støtteanalyse', stoettearbeid:'støttearbeid', stoettebehov:'støttebehov', stoettedata:'støttedata', stoetter:'støtter', Stoette:'Støtte',
  stotteinformasjonen:'støtteinformasjonen', produktstoette:'produktstøtte', Produktstoette:'Produktstøtte', produktstoetteinformasjon:'produktstøtteinformasjon', logistikkstoette:'logistikkstøtte', logistikkstoetteanalyse:'logistikkstøtteanalyse',
  fartoy:'fartøy', fartoyet:'fartøyet', fartoyets:'fartøyets', Fartoyets:'Fartøyets', fartoyidentitet:'fartøyidentitet', fartoyprogram:'fartøyprogram', fartoyprosjekt:'fartøyprosjekt',
  synliggjoer:'synliggjør', Undersoek:'Undersøk', undersoek:'undersøk', undersoeke:'undersøke', utfoert:'utført', vaere:'være', viderefoerer:'viderefører'
};

function normalizeNorwegianText(value) {
  if (typeof value === 'string') return value.replace(/\b[A-Za-z]+\b/g, (word) => norwegianWordCorrections[word] || word.replace(/aa/g, 'å'));
  if (Array.isArray(value)) return value.map(normalizeNorwegianText);
  if (value && typeof value === 'object') {
    Object.keys(value).forEach((key) => {
      value[key] = normalizeNorwegianText(value[key]);
    });
  }
  return value;
}

normalizeNorwegianText(window.hicoLearningData);
